language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
env:
  - PYTHONPATH=./:libs/

install: 
  - pip install -r requirements_core.txt
  - pip install coveralls
  - python manage.py syncdb --noinput
# command to run tests
script: 
  - coverage run --source=webapp ./manage.py test --settings webapp.settings_tests
after_success:
  - coveralls 